name: Build Tauri Windows (NSIS)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Tauri CLI (v1)
        run: cargo install tauri-cli --version ^1 --locked
        shell: pwsh

      - name: Show versions (debug)
        run: |
          rustc -V
          cargo -V
          cargo tauri -V
        shell: pwsh

      - name: Build (NSIS)
        working-directory: src-tauri
        run: cargo tauri build --target x86_64-pc-windows-msvc --bundles nsis
        shell: pwsh

      - name: Upload NSIS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReconcileTool-NSIS
          path: src-tauri/target/release/bundle/nsis/*.exe
